-- ============================================================================
-- Harcourt Educational Consult — Phase 1: self-hosted auth
-- Replaces Supabase Auth (email rate limits, confirmation emails) with our own
-- users, hashed passwords, and revocable sessions. Google sign-in slots in
-- later against the same credentials table.
--
-- Apply: Supabase Dashboard → SQL Editor (paste & run). Safe to re-run.
--
-- What this changes:
--   1. profiles.id is decoupled from auth.users (own UUIDs from now on)
--   2. credentials  — email + password hash. DENY-ALL RLS (server-only)
--   3. sessions     — opaque tokens, SHA-256 hashed at rest, expiring
--   4. register_user RPC — atomic signup (profile + credentials)
--   5. Admin RPCs now take the acting admin's id and verify it against the
--      profiles table (no JWT dependency)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1) Decouple profiles from auth.users.
--    Old rows keep their ids; new ids are generated by register_user().
-- ---------------------------------------------------------------------------
alter table public.profiles
  drop constraint if exists profiles_id_fkey;

-- ---------------------------------------------------------------------------
-- 2) Credentials — the only place password hashes live.
--    No RLS policies on purpose: anon/authenticated can never touch it; only
--    the server (service_role key, which bypasses RLS) reads or writes.
-- ---------------------------------------------------------------------------
create extension if not exists citext;

create table if not exists public.credentials (
  profile_id    uuid primary key references public.profiles (id) on delete cascade,
  email         citext not null unique,
  password_hash text not null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
-- (citext's unique constraint already indexes email.)

-- ---------------------------------------------------------------------------
-- 3) Sessions — opaque random tokens; only their SHA-256 hash is stored.
--    A leaked database dump cannot be replayed to hijack sessions.
-- ---------------------------------------------------------------------------
create table if not exists public.sessions (
  token_hash text primary key,
  profile_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

create index if not exists idx_sessions_profile on public.sessions (profile_id);

alter table public.credentials enable row level security;
alter table public.sessions    enable row level security;
-- (No policies: every path is denied to anon/authenticated roles.)

-- ---------------------------------------------------------------------------
-- 4) register_user — atomic signup. Returns the new profile id.
--    Self-registration as 'admin' is impossible; unknown roles fall back.
-- ---------------------------------------------------------------------------
create or replace function public.register_user(
  p_email         text,
  p_password_hash text,
  p_full_name     text default '',
  p_role          public.user_role default 'student'
) returns uuid
language plpgsql
security definer set search_path = public
as $$
declare
  new_id     uuid := gen_random_uuid();
  final_role public.user_role := p_role;
begin
  if final_role = 'admin' then
    final_role := 'student';
  end if;

  insert into public.profiles (id, full_name, role)
  values (new_id, coalesce(nullif(trim(p_full_name), ''), ''), final_role);

  insert into public.credentials (profile_id, email, password_hash)
  values (new_id, lower(trim(p_email)), p_password_hash);

  return new_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5) Actor identity for admin operations.
--    is_admin(p_uid) checks the profiles table directly — no JWT involved.
-- ---------------------------------------------------------------------------
create or replace function public.is_admin(p_uid uuid)
returns boolean
language sql stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles where id = p_uid and role = 'admin'
  );
$$;

-- ---------------------------------------------------------------------------
-- 6) Status guard — only an identified admin may change verification_status.
--    The acting admin id is passed via the request.harcot.actor_id GUC, which
--    is only ever set by the security-definer RPCs below AFTER they verify
--    the caller is a real admin.
-- ---------------------------------------------------------------------------
create or replace function public.tutor_profile_status_guard()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  actor uuid := nullif(current_setting('request.harcot.actor_id', true), '')::uuid;
begin
  if new.verification_status is distinct from old.verification_status then
    if actor is null or not public.is_admin(actor) then
      raise exception 'forbidden: only admins may change verification status';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists tutor_profile_status_guard on public.tutor_profiles;
create trigger tutor_profile_status_guard
  before update on public.tutor_profiles
  for each row execute function public.tutor_profile_status_guard();

-- ---------------------------------------------------------------------------
-- 6b) Drop the JWT-era admin RPC overloads from 0001 (they keyed off
--     auth.jwt(), which is meaningless now). Keeps a single, unambiguous
--     signature per RPC.
-- ---------------------------------------------------------------------------
drop function if exists public.admin_approve_tutor(uuid, text);
drop function if exists public.admin_reject_tutor(uuid, text);

-- ---------------------------------------------------------------------------
-- 7) Admin RPCs — atomic approve/reject + immutable audit trail.
--    Caller passes the acting admin's profile id; the DB re-verifies it.
-- ---------------------------------------------------------------------------
create or replace function public.admin_approve_tutor(
  actor_id  uuid,
  target_id uuid,
  note      text default null
) returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin(actor_id) then
    raise exception 'forbidden: admin only';
  end if;
  perform set_config('request.harcot.actor_id', actor_id::text, true);

  update public.tutor_profiles
  set verification_status = 'approved',
      admin_notes         = note,
      reviewed_at         = now(),
      updated_at          = now()
  where id = target_id;

  insert into public.admin_audit_log (admin_id, action, target_type, target_id, metadata)
  values (actor_id, 'approve_tutor', 'tutor_profile', target_id,
          jsonb_build_object('note', note));
end;
$$;

create or replace function public.admin_reject_tutor(
  actor_id  uuid,
  target_id uuid,
  note      text
) returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin(actor_id) then
    raise exception 'forbidden: admin only';
  end if;
  perform set_config('request.harcot.actor_id', actor_id::text, true);

  update public.tutor_profiles
  set verification_status = 'rejected',
      admin_notes         = note,
      reviewed_at         = now(),
      updated_at          = now()
  where id = target_id;

  insert into public.admin_audit_log (admin_id, action, target_type, target_id, metadata)
  values (actor_id, 'reject_tutor', 'tutor_profile', target_id,
          jsonb_build_object('note', note));
end;
$$;
